"""empty message

Revision ID: 016acd18ea22
Revises: c05bb26d1198
Create Date: 2025-02-11 11:36:34.232968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '016acd18ea22'
down_revision: Union[str, None] = 'c05bb26d1198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('execution', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generator_details',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('license_start_date', sa.Date(), nullable=True),
    sa.Column('license_end_date', sa.Date(), nullable=True),
    sa.Column('tp_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('komrad_details',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('license_start_date', sa.Date(), nullable=True),
    sa.Column('license_end_date', sa.Date(), nullable=True),
    sa.Column('tp_type', sa.String(length=20), nullable=True),
    sa.Column('license_type', sa.String(length=20), nullable=True),
    sa.Column('tp_start_date', sa.Date(), nullable=True),
    sa.Column('tp_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('pik_details',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('license_start_date', sa.Date(), nullable=True),
    sa.Column('license_end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('rubicon_details',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('scaner_details',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('license_start_date', sa.Date(), nullable=True),
    sa.Column('license_end_date', sa.Date(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('additional_ip', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scaner_details')
    op.drop_table('rubicon_details')
    op.drop_table('pik_details')
    op.drop_table('komrad_details')
    op.drop_table('generator_details')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
